### ISSUE TITLE
LiveCam: improve positioning

### ISSUE THREAD

**Issue by silmiras** [teamsquad-io/amateur-tv#18]
We need that block:
- [x] behave like any other standard block
- [x] the iframe should have 100% width to fit the block width, whatever it is
- [x] it shouldn't have a ; symbol at the end of the block

**Comment by contactashish13** [comment]
@silmiras PR https://github.com/teamsquad-io/amateur-tv/pull/22 is ready for review.

**Comment by silmiras** [comment]
@contactashish13 with options on "none" and "center" it is having a huge blank space on the bottom of the cam. Is it possible to set up a height?
![blank_space_bottom](https://user-images.githubusercontent.com/123000179/222038992-c3f620ac-ef0b-4d5c-bb96-364b49462a3b.png)

**Comment by contactashish13** [comment]
@silmiras for some reason you are testing the changes in #19 here instead of the changes that were made for this issue. The iframe width for this issue was made as 100% but in the page I can see that the width is in pixels:

![image](https://user-images.githubusercontent.com/12953439/222057352-a52008d3-84e6-41f1-84e7-ed538a311ec5.png)

Can you please make sure that you are testing the correct issue? 

To avoid confusion, in the future I will add the issue number to the version of the plugin so that it is apparent which issue you are testing.

**Comment by contactashish13** [comment]
@silmiras I have added an option for iframe height. Can you please test and see if it fits your needs?

**Comment by contactashish13** [comment]
@javiercasares I'm not sure this should have been merged as @silmiras still hadn't tested this
